sudo: required
services:
  - docker

before_install:
  - docker build -t mhomaid/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mhomaid/react-test npm test

after_success:
  - docker build -t mhomaid/multi-client ./client
  - docker build -t mhomaid/multi-nginx ./nginx
  - docker build -t mhomaid/multi-server ./server
  - docker build -t mhomaid/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub 
  - docker push mhomaid/multi-client
  - docker push mhomaid/multi-nginx
  - docker push mhomaid/multi-server
  - docker push mhomaid/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name:  elasticbeanstalk-us-east-2-199194989426
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

